name: file_share_app
description: "A high-speed file sharing application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For file picking and folder paths
  file_picker: ^6.2.0
  path_provider: ^2.1.3
  path: ^1.9.0

  # For getting the local IP address
  network_info_plus: ^5.0.3

  # For Lottie animations
  lottie: ^3.1.2

  # For requesting permissions on iOS
  permission_handler: ^11.3.1

  # For the advanced asset picker (photos and videos)
  wechat_assets_picker: ^9.1.0

  # Fixes potential conflicts with other packages
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # A stable version of the lints package
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
 
  assets:
    - assets/profile.png
    - assets/transfer_complete.json
    - assets/fonts/
 
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Semibold.ttf
          weight: 600
