name: Build Unsigned Flutter iOS App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        # --- THIS IS THE FIX ---
        # Force the runner to use the new Flutter version
        flutter-version: '3.35.4' 
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Build unsigned .app bundle
      run: flutter build ios --release --no-codesign

    - name: Package the unsigned .ipa
      run: |
        mkdir -p Payload
        mv build/ios/iphoneos/Runner.app Payload/Runner.app
        zip -r -y file_share.ipa Payload

    - name: Upload Unsigned IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-ipa
        path: file_share.ipa
